---
version: "2.0"
services:
  app:
    image: arealicehole/justice-watch:prod.01
    expose:
      - port: 3001
        as: 80
        to:
          - global: true
    env:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SUPABASE_URL=https://tsgvxobkmmvsbjzxvuas.supabase.co
      - >-
        SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZ3Z4b2JrbW12c2Jqenh2dWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDYwMTAsImV4cCI6MjA3MDY4MjAxMH0.yp6jmeABzFdbvydiLJ4tXLEDT38tlDzkDoD8KWr-yv4
      - >-
        SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZ3Z4b2JrbW12c2Jqenh2dWFzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTEwNjAxMCwiZXhwIjoyMDcwNjgyMDEwfQ.8HVnQhpnLHFWKPDaX7AnlydJ_dVu7mErl1YBs43Rl4k
      - >-
        DATABASE_URL=postgresql://postgres.tsgvxobkmmvsbjzxvuas:Johnnyboy2444!@aws-0-us-west-1.pooler.supabase.com:6543/postgres?pgbouncer=true
      - JWT_SECRET=6KnV07LtADeznJLZKyjvAGUfJzftCt+1RS13B/B6g1M=
      - SESSION_SECRET=MZYo44hV4KsFiY+xaCygC2SU7VxP8KdtOkXWvhG576A=
  redis:
    image: redis:7-alpine
    expose:
      - port: 6379
        as: 6379
        to:
          - global: false
          - service: app
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          - size: 10Gi
    redis:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          - size: 5Gi
  placement:
    akash:
      pricing:
        app:
          denom: uakt
          amount: 500
        redis:
          denom: uakt
          amount: 100
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
          - akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4
      attributes:
        host: akash
deployment:
  app:
    akash:
      profile: app
      count: 1
  redis:
    akash:
      profile: redis
      count: 1
