#!/usr/bin/env python3
"""
Manual Supabase Database Setup Guide
Since Supabase doesn't support direct SQL execution via Python client,
this script generates the necessary SQL and provides setup instructions.
"""

import os
import sys
from pathlib import Path
from typing import Dict

try:
    from dotenv import load_dotenv
    from supabase import create_client, Client
except ImportError:
    print("Installing required packages...")
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "python-dotenv", "supabase"])
    from dotenv import load_dotenv
    from supabase import create_client, Client

def load_credentials() -> Dict[str, str]:
    """Load Supabase credentials from .env.github"""
    env_file = '.env.github'
    if not os.path.exists(env_file):
        raise FileNotFoundError(f"{env_file} not found!")
    
    load_dotenv(env_file)
    
    credentials = {
        'url': os.getenv('SUPABASE_URL'),
        'anon_key': os.getenv('SUPABASE_ANON_KEY'),
        'service_key': os.getenv('SUPABASE_SERVICE_KEY'),
    }
    
    missing = [k for k, v in credentials.items() if not v]
    if missing:
        raise ValueError(f"Missing credentials: {', '.join(missing)}")
    
    return credentials

def generate_combined_sql() -> str:
    """Combine all SQL files into one script"""
    sql_files = [
        "supabase/migrations/20250117_justice_watch_schema.sql",
        "supabase/migrations/001_cron_scheduler.sql"
    ]
    
    combined_sql = """-- Justice Watch Production Database Setup
-- Generated by setup_database_manual.py
-- Execute this in Supabase SQL Editor

"""
    
    for sql_file in sql_files:
        if os.path.exists(sql_file):
            combined_sql += f"\n-- ========================================\n"
            combined_sql += f"-- {sql_file}\n"
            combined_sql += f"-- ========================================\n\n"
            
            with open(sql_file, 'r') as f:
                combined_sql += f.read()
            
            combined_sql += "\n\n"
        else:
            print(f"⚠️  Warning: {sql_file} not found")
    
    return combined_sql

def create_verification_sql() -> str:
    """Create SQL for verifying the setup"""
    return """-- Verification Queries
-- Run these to verify your database setup

-- 1. Check all tables exist
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_name IN ('cases', 'case_parties', 'case_charges', 'case_calendar', 'cron_schedules', 'cron_executions')
ORDER BY table_name;

-- 2. Check RLS is enabled
SELECT tablename, rowsecurity 
FROM pg_tables 
WHERE schemaname = 'public' 
AND tablename IN ('cases', 'case_parties', 'case_charges', 'case_calendar')
ORDER BY tablename;

-- 3. Test database functions
SELECT get_case_stats();

-- 4. Check indexes exist
SELECT indexname, tablename 
FROM pg_indexes 
WHERE schemaname = 'public' 
AND tablename IN ('cases', 'case_parties', 'case_charges', 'case_calendar')
ORDER BY tablename, indexname;

-- 5. Verify policies exist
SELECT policyname, tablename, cmd, roles 
FROM pg_policies 
WHERE schemaname = 'public'
ORDER BY tablename, policyname;
"""

def test_connection(credentials: Dict[str, str]) -> bool:
    """Test connection to Supabase"""
    try:
        # Test with anonymous key
        anon_client = create_client(credentials['url'], credentials['anon_key'])
        # Simple connection test - this will work even with empty database
        print("✅ Anonymous client connection successful")
        
        # Test with service key  
        service_client = create_client(credentials['url'], credentials['service_key'])
        print("✅ Service role client connection successful")
        
        return True
    except Exception as e:
        print(f"❌ Connection test failed: {e}")
        return False

def main():
    print("=" * 70)
    print("Supabase Production Database Setup - Manual Mode")
    print("=" * 70)
    
    try:
        # Load credentials
        print("\n📋 Loading credentials...")
        credentials = load_credentials()
        print(f"✅ Loaded credentials for: {credentials['url']}")
        
        # Test connection
        print("\n🔌 Testing connection...")
        if not test_connection(credentials):
            return False
        
        # Generate SQL files
        print("\n📝 Generating SQL scripts...")
        
        # Combined setup SQL
        combined_sql = generate_combined_sql()
        setup_file = "database_setup_combined.sql"
        with open(setup_file, 'w') as f:
            f.write(combined_sql)
        print(f"✅ Created {setup_file}")
        
        # Verification SQL
        verification_sql = create_verification_sql()
        verify_file = "database_verification.sql"
        with open(verify_file, 'w') as f:
            f.write(verification_sql)
        print(f"✅ Created {verify_file}")
        
        # Instructions
        print("\n" + "=" * 70)
        print("📋 MANUAL SETUP INSTRUCTIONS")
        print("=" * 70)
        
        print(f"\n🌐 1. Go to your Supabase Dashboard:")
        print(f"   {credentials['url'].replace('https://', 'https://supabase.com/dashboard/project/')}")
        
        print(f"\n📊 2. Navigate to SQL Editor:")
        print(f"   • Click 'SQL Editor' in the left sidebar")
        print(f"   • Click 'New Query'")
        
        print(f"\n📋 3. Execute the setup script:")
        print(f"   • Copy contents of: {setup_file}")
        print(f"   • Paste into SQL Editor")
        print(f"   • Click 'Run' button")
        
        print(f"\n✅ 4. Verify the setup:")
        print(f"   • Open a new query in SQL Editor") 
        print(f"   • Copy contents of: {verify_file}")
        print(f"   • Run each query section to verify")
        
        print(f"\n🔐 5. Expected Results:")
        print(f"   • 6 tables created (cases, case_parties, case_charges, case_calendar, cron_schedules, cron_executions)")
        print(f"   • RLS enabled on core tables")
        print(f"   • Multiple indexes created for performance")
        print(f"   • Database functions working")
        print(f"   • Public read and service write policies active")
        
        print(f"\n🎯 6. Test from your app:")
        print(f"   • Frontend: Use anon key {credentials['anon_key'][:20]}... for reads")
        print(f"   • Scrapers: Use service key for writes (already in GitHub secrets)")
        
        print(f"\n⚠️  Important Notes:")
        print(f"   • If you see 'already exists' errors, that's normal - skip them")
        print(f"   • All core functionality should work after setup")
        print(f"   • Real-time subscriptions will work automatically")
        print(f"   • GitHub Actions are already configured with secrets")
        
        print(f"\n🚀 After setup, your Justice Watch app will be ready for production!")
        
        return True
        
    except Exception as e:
        print(f"\n❌ Setup preparation failed: {e}")
        return False

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)